/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/RocketList copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListRockets: typeof import('./src/components/ListRockets.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RocketDetail: typeof import('./src/components/RocketDetail.vue')['default']
    RocketList: typeof import('./src/components/RocketList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/components/Toast.vue')['default']
  }
}
